Ola ramalho, como podes ver eu sabia que nao ias resistir e abrir este ficheiro.
Agora estas te a rir.
Agora ja nao.
Pensa no numero de 0 a 10
Esse numero é...
...
...
...
...
7
Acertei ?
Provalvelmente nao.
Mas uma coisa é certa 
Es um paneileiro de merda
